import '../../vro-el-image/style/deps'
import 'element-plus/es/components/checkbox/style/css'
import 'element-plus/es/components/icon/style/css'
import 'element-plus/es/components/image/style/css'
import 'element-plus/es/components/loading/style/css'
