/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
    VroAspectRatio: typeof import('@vrojs/base')['VroAspectRatio']
    VroElCheckboxGroup: typeof import('@vrojs/element-plus')['VroElCheckboxGroup']
    VroElConfigProvider: typeof import('@vrojs/element-plus')['VroElConfigProvider']
    VroElFileUpload: typeof import('@vrojs/element-plus')['VroElFileUpload']
    VroElIcon: typeof import('@vrojs/element-plus')['VroElIcon']
    VroElImage: typeof import('@vrojs/element-plus')['VroElImage']
    VroElImageUpload: typeof import('@vrojs/element-plus')['VroElImageUpload']
    VroElRadioGroup: typeof import('@vrojs/element-plus')['VroElRadioGroup']
    VroElSchemaFilter: typeof import('@vrojs/element-plus')['VroElSchemaFilter']
    VroElSchemaForm: typeof import('@vrojs/element-plus')['VroElSchemaForm']
    VroElSchemaFormDialog: typeof import('@vrojs/element-plus')['VroElSchemaFormDialog']
    VroElSelect: typeof import('@vrojs/element-plus')['VroElSelect']
    VroElSkeleton: typeof import('@vrojs/element-plus')['VroElSkeleton']
    VroElTags: typeof import('@vrojs/element-plus')['VroElTags']
    VroElTree: typeof import('@vrojs/element-plus')['VroElTree']
    VroElWithConfig: typeof import('@vrojs/element-plus')['VroElWithConfig']
    VroInput: typeof import('@vrojs/base')['VroInput']
    VroLoading: typeof import('@vrojs/base')['VroLoading']
    VroVanCell: typeof import('@vrojs/vant')['VroVanCell']
    VroVanIcon: typeof import('@vrojs/vant')['VroVanIcon']
    VroVanTest: typeof import('@vrojs/vant')['VroVanTest']
    VroVnr: typeof import('@vrojs/base')['VroVnr']
  }
}
