/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VroAspectRatio: typeof import('@vrojs/base')['VroAspectRatio']
    VroElCheckboxGroup: typeof import('@vrojs/element-plus')['VroElCheckboxGroup']
    VroElConfigProvider: typeof import('@vrojs/element-plus')['VroElConfigProvider']
    VroElFileUpload: typeof import('@vrojs/element-plus')['VroElFileUpload']
    VroElIcon: typeof import('@vrojs/element-plus')['VroElIcon']
    VroElImage: typeof import('@vrojs/element-plus')['VroElImage']
    VroElImageUpload: typeof import('@vrojs/element-plus')['VroElImageUpload']
    VroElRadioGroup: typeof import('@vrojs/element-plus')['VroElRadioGroup']
    VroElSchemaFilter: typeof import('@vrojs/element-plus')['VroElSchemaFilter']
    VroElSchemaForm: typeof import('@vrojs/element-plus')['VroElSchemaForm']
    VroElSchemaFormDialog: typeof import('@vrojs/element-plus')['VroElSchemaFormDialog']
    VroElSelect: typeof import('@vrojs/element-plus')['VroElSelect']
    VroElSkeleton: typeof import('@vrojs/element-plus')['VroElSkeleton']
    VroElTable: typeof import('@vrojs/element-plus')['VroElTable']
    VroElTableActionsColumn: typeof import('@vrojs/element-plus')['VroElTableActionsColumn']
    VroElTableColumn: typeof import('@vrojs/element-plus')['VroElTableColumn']
    VroElTableColumnGroup: typeof import('@vrojs/element-plus')['VroElTableColumnGroup']
    VroElTags: typeof import('@vrojs/element-plus')['VroElTags']
    VroElTree: typeof import('@vrojs/element-plus')['VroElTree']
    VroElWithConfig: typeof import('@vrojs/element-plus')['VroElWithConfig']
    VroIcon: typeof import('@vrojs/base')['VroIcon']
    VroInput: typeof import('@vrojs/base')['VroInput']
    VroLoading: typeof import('@vrojs/base')['VroLoading']
    VroVanActionSheet: typeof import('@vrojs/vant')['VroVanActionSheet']
    VroVanCell: typeof import('@vrojs/vant')['VroVanCell']
    VroVanCellGroup: typeof import('@vrojs/vant')['VroVanCellGroup']
    VroVanCheckbox: typeof import('@vrojs/vant')['VroVanCheckbox']
    VroVanCheckboxButton: typeof import('@vrojs/vant')['VroVanCheckboxButton']
    VroVanConfigProvider: typeof import('@vrojs/vant')['VroVanConfigProvider']
    VroVanDatetimePicker: typeof import('@vrojs/vant')['VroVanDatetimePicker']
    VroVanDateTimePicker: typeof import('@vrojs/vant')['VroVanDateTimePicker']
    VroVanDatetimeRangeSelectPicker: typeof import('@vrojs/vant')['VroVanDatetimeRangeSelectPicker']
    VroVanDatetimeSelectPicker: typeof import('@vrojs/vant')['VroVanDatetimeSelectPicker']
    VroVanField: typeof import('@vrojs/vant')['VroVanField']
    VroVanIcon: typeof import('@vrojs/vant')['VroVanIcon']
    VroVanPicker: typeof import('@vrojs/vant')['VroVanPicker']
    VroVanRadio: typeof import('@vrojs/vant')['VroVanRadio']
    VroVanRadioButton: typeof import('@vrojs/vant')['VroVanRadioButton']
    VroVanScroll: typeof import('@vrojs/vant')['VroVanScroll']
    VroVanSelectPicker: typeof import('@vrojs/vant')['VroVanSelectPicker']
    VroVanSkeleton: typeof import('@vrojs/vant')['VroVanSkeleton']
    VroVanTest: typeof import('@vrojs/vant')['VroVanTest']
    VroVanTextarea: typeof import('@vrojs/vant')['VroVanTextarea']
    VroVanTriggerCell: typeof import('@vrojs/vant')['VroVanTriggerCell']
    VroVnr: typeof import('@vrojs/base')['VroVnr']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
