/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanField: typeof import('vant/es')['Field']
    VroAspectRatio: typeof import('@vrojs/base')['VroAspectRatio']
    VroElCheckboxGroup: typeof import('@vrojs/element-plus')['VroElCheckboxGroup']
    VroElConfigProvider: typeof import('@vrojs/element-plus')['VroElConfigProvider']
    VroElFileUpload: typeof import('@vrojs/element-plus')['VroElFileUpload']
    VroElIcon: typeof import('@vrojs/element-plus')['VroElIcon']
    VroElImage: typeof import('@vrojs/element-plus')['VroElImage']
    VroElImageUpload: typeof import('@vrojs/element-plus')['VroElImageUpload']
    VroElRadioGroup: typeof import('@vrojs/element-plus')['VroElRadioGroup']
    VroElSchemaFilter: typeof import('@vrojs/element-plus')['VroElSchemaFilter']
    VroElSchemaForm: typeof import('@vrojs/element-plus')['VroElSchemaForm']
    VroElSchemaFormDialog: typeof import('@vrojs/element-plus')['VroElSchemaFormDialog']
    VroElSelect: typeof import('@vrojs/element-plus')['VroElSelect']
    VroElSkeleton: typeof import('@vrojs/element-plus')['VroElSkeleton']
    VroElTable: typeof import('@vrojs/element-plus')['VroElTable']
    VroElTableColumn: typeof import('@vrojs/element-plus')['VroElTableColumn']
    VroElTableColumnGroup: typeof import('@vrojs/element-plus')['VroElTableColumnGroup']
    VroElTags: typeof import('@vrojs/element-plus')['VroElTags']
    VroElTree: typeof import('@vrojs/element-plus')['VroElTree']
    VroElWithConfig: typeof import('@vrojs/element-plus')['VroElWithConfig']
    VroIcon: typeof import('@vrojs/base')['VroIcon']
    VroInput: typeof import('@vrojs/base')['VroInput']
    VroLoading: typeof import('@vrojs/base')['VroLoading']
    VroVanCell: typeof import('@vrojs/vant')['VroVanCell']
    VroVanCellGroup: typeof import('@vrojs/vant')['VroVanCellGroup']
    VroVanCheckbox: typeof import('@vrojs/vant')['VroVanCheckbox']
    VroVanCheckboxButton: typeof import('@vrojs/vant')['VroVanCheckboxButton']
    VroVanConfigProvider: typeof import('@vrojs/vant')['VroVanConfigProvider']
    VroVanField: typeof import('@vrojs/vant')['VroVanField']
    VroVanIcon: typeof import('@vrojs/vant')['VroVanIcon']
    VroVanRadio: typeof import('@vrojs/vant')['VroVanRadio']
    VroVanRadioButton: typeof import('@vrojs/vant')['VroVanRadioButton']
    VroVanTextarea: typeof import('@vrojs/vant')['VroVanTextarea']
    VroVanTriggerCell: typeof import('@vrojs/vant')['VroVanTriggerCell']
    VroVnr: typeof import('@vrojs/base')['VroVnr']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
